// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcodxGH_kIvQndGK90LVQDxghWlPM82E',
    appId: '1:609093417154:web:cd4aa81913bf43aaa5235b',
    messagingSenderId: '609093417154',
    projectId: 'login-flutter-95a27',
    authDomain: 'login-flutter-95a27.firebaseapp.com',
    storageBucket: 'login-flutter-95a27.firebasestorage.app',
    measurementId: 'G-WJ5EHHK2F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fB1qHjepJelZ6VvM70a5uZpGObZ5Lgg',
    appId: '1:609093417154:android:65bea2ec4729dfe4a5235b',
    messagingSenderId: '609093417154',
    projectId: 'login-flutter-95a27',
    storageBucket: 'login-flutter-95a27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXH_BJE5PVrDuYtj9NwW2hOnfmJsj0JAs',
    appId: '1:609093417154:ios:f450e3176bcfb5cda5235b',
    messagingSenderId: '609093417154',
    projectId: 'login-flutter-95a27',
    storageBucket: 'login-flutter-95a27.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXH_BJE5PVrDuYtj9NwW2hOnfmJsj0JAs',
    appId: '1:609093417154:ios:f450e3176bcfb5cda5235b',
    messagingSenderId: '609093417154',
    projectId: 'login-flutter-95a27',
    storageBucket: 'login-flutter-95a27.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcodxGH_kIvQndGK90LVQDxghWlPM82E',
    appId: '1:609093417154:web:5482eee9deab120fa5235b',
    messagingSenderId: '609093417154',
    projectId: 'login-flutter-95a27',
    authDomain: 'login-flutter-95a27.firebaseapp.com',
    storageBucket: 'login-flutter-95a27.firebasestorage.app',
    measurementId: 'G-KC0PV25EPK',
  );

}